### ISSUE TITLE
header parsing support maybe

### ISSUE THREAD

**Issue by erisdev** [jacius/nice-ffi#1]
I found this project through chipmunk-ffi, and it (and ruby-ffi also) is pretty damned cool. Since you're adding more nice to FFI, are there any plans to add C header parsing or anything similar? If not, and if you feel that it is within the scope of what you want to do, then consider this my formal request. It would drastically reduce code duplication for projects using it. :)

Short version: I'd like to see support for parsing C headers to automatically create library interfaces.

**Comment by jacius** [comment]
[ffi-swig-generator](http://github.com/ffi/ffi-swig-generator/) does _almost_ that, but you have to first use SWIG to convert the headers into an xml file.

I've just added [instructions for that](http://wiki.github.com/ffi/ffi-swig-generator) to the ffi-swig-generator wiki. Give it a look. :)
