### ISSUE TITLE
NameError: uninitialized constant NiceFFI::PathSet::DEFAULT_PATHS

### ISSUE THREAD

**Issue by utgarda** [jacius/nice-ffi#2]
NameError: uninitialized constant NiceFFI::PathSet::DEFAULT_PATHS
        from /home/etsvigun/.gem/ruby/1.8/gems/nice-ffi-0.3/lib/nice-ffi/library.rb:68:in `load_library'
        from /home/etsvigun/.gem/ruby/1.8/gems/chipmunk-ffi-1.0.0/lib/chipmunk-ffi.rb:25
...
I guess, library.rb:68 here 28d7cb6e4ad039e19e17e4015f920ea0ce347f6f should really be
def load_library( names, search_paths=NiceFFI::PathSet::DEFAULT)

**Comment by jacius** [comment]
Ah, you're right. Fixed in 0e51a6fc4a95ebb66f2e7e5f304878b1ff60ff48. Thanks for the report!
